### ISSUE TITLE
tienes como hacer un porting a otro lenguaje que  sea multiplataforma

### ISSUE THREAD

**Issue by daverod24** [GusGA/lechuga#3]
hola  me  gustaria  saber  de  donde  sacas el precio referencial del  efectivo y trasferencia  para  portarlo a python  y  que  sea multiplataforma

**Comment by GusGA** [comment]
Saludos

La info la tomo de dolartoday y pero logré exportarla en formato JSON para que puede ser consumida como endpoint para distintas aplicaciones

La url es `https://lechuga.herokuapp.com` con esto se salta los bloqueos que le tienen impuesto a DT y otras web.

Bienvenido eres a usarlo y me comentas como va tu proyecto :beers:
